---
- hosts: webservers
  remote_user: ec2-user
  become: yes
  become_user: root
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: ensure tomcat is at the latest version
    yum: name=tomcat state=latest
    notify:
    - restart tomcat
  - name: ensure tomcat is running
    service: name=tomcat state=started
  handlers:
  - name: restart tomcat
    service: name=tomcat start=restarted
