---
- hosts: webservers
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
  - name: make sure all OS patches are applied
    yum: pkg=httpd state=latest
  - name: install git 
    yum:  pkg=git state=installed
